-- require("color")
-- require("fugititve")
-- require("lsp")
-- require("lualine")
-- require("telescope")
-- require("treesitter")
-- require("undotree")
-- require("indentBlankLine")
-- require("harpoon")

-- require("Demi.PluginConfig.color")
require("Demi.PluginConfig.fugititve")
require("Demi.PluginConfig.lsp")
require("Demi.PluginConfig.lualine")
require("Demi.PluginConfig.telescope")
require("Demi.PluginConfig.undotree")
require("Demi.PluginConfig.indentBlankLine")
require("Demi.PluginConfig.harpoon")
require("Demi.PluginConfig.treesitter")
